CREATE TABLE AGENT_ (
  AGENT_ID NUMBER NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  ADDRESS VARCHAR2(50) NOT NULL,
  BANK_DETAILS VARCHAR2(50) NOT NULL,
  CONSTRAINT AGENT_PK PRIMARY KEY (AGENT_ID)
);

CREATE TABLE PRODUCT_ (
  PRODUCT_ID NUMBER NOT NULL,
  CATEGORY_ID NUMBER NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  DETAILS varchar(50),
  CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE PRODUCT_CATEGORY_ (
  CATEGORY_ID NUMBER NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  CONSTRAINT PRODUCT_CATEGORY_PK PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE STOCK_PRODUCT_ (
  PRODUCT_ID NUMBER NOT NULL,
  AMOUNT NUMBER NOT NULL,
  CONSTRAINT STOCK_PRODUCT_PK PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE STOCK_ARRIVAL_ (
  ARRIVAL_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  ARRIVAL_DATE date NOT NULL,
  AMOUNT NUMBER NOT NULL,
  CONSTRAINT STOCK_ARRIVAL_PK PRIMARY KEY (ARRIVAL_ID)
);

CREATE TABLE STOCK_SHIPMENT_ (
  SHIPMENT_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  SHIPMENT_DATE date NOT NULL,
  AMOUNT NUMBER NOT NULL,
  CONSTRAINT STOCK_SHIPMENT_PK PRIMARY KEY (SHIPMENT_ID)
);

CREATE TABLE DEAL_DELIVERY_ (
  DELIVERY_ID NUMBER NOT NULL,
  AGENT_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  PRICE NUMBER NOT NULL,
  DELIVERY_DATE date NOT NULL,
  CONSTRAINT DEAL_DELIVERY_PK PRIMARY KEY (DELIVERY_ID)
);

CREATE TABLE DEAL_SHIPMENT_ (
  SHIPMENT_ID NUMBER NOT NULL,
  AGENT_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  PRICE NUMBER NOT NULL,
  SHIPMENT_DATE date NOT NULL,
  CONSTRAINT DEAL_SHIPMENT_PK PRIMARY KEY (SHIPMENT_ID)
);

CREATE TABLE WAYBILL_DELIVERY_ (
  WAYBILL_ID NUMBER NOT NULL,
  AGENT_ID NUMBER NOT NULL,
  WAYBILL_DATE date NOT NULL,
  DELIVERY_PRICE NUMBER NOT NULL,
  CONSTRAINT WAYBILL_DELIVERY_PK PRIMARY KEY (WAYBILL_ID)
);

CREATE TABLE WAYBILL_SHIPMENT_ (
  WAYBILL_ID NUMBER NOT NULL,
  AGENT_ID NUMBER NOT NULL,
  WAYBILL_DATE date NOT NULL,
  SHIPMENT_PRICE NUMBER NOT NULL,
  CONSTRAINT WAYBILL_SHIPMENT_PK PRIMARY KEY (SHIPMENT_ID)
);

CREATE TABLE WB_PR_DELIVERY_ (
  WB_ID NUMBER NOT NULL,
  PR_ID NUMBER NOT NULL,
  AMOUNT NUMBER NOT NULL,
  CONSTRAINT WB_PR_DELIVERY_PK PRIMARY KEY (WB_ID, PR_ID)
);

CREATE TABLE WB_PR_CHARGED_ (
  WB_ID NUMBER NOT NULL,
  PR_ID NUMBER NOT NULL,
  AMOUNT NUMBER NOT NULL,
  CONSTRAINT WB_PR_CHARGED_PK PRIMARY KEY (WB_ID, PR_ID)
);

CREATE TABLE WB_PR_SHIPMENT_ (
  WB_ID NUMBER NOT NULL,
  PR_ID NUMBER NOT NULL,
  AMOUNT NUMBER NOT NULL,
  CONSTRAINT WB_PR_SHIPMENT_PK PRIMARY KEY (WB_ID, PR_ID)
);

ALTER TABLE PRODUCT_
ADD CONSTRAINT PRODUCT_FK1
FOREIGN KEY (CATEGORY_ID)
REFERENCES CATEGORY_ (CATEGORY_ID);

ALTER TABLE STOCK_PRODUCT_
ADD CONSTRAINT STOCK_PRODUCT_FK1
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT_ (PRODUCT_ID);

ALTER TABLE STOCK_SHIPMENT_
ADD CONSTRAINT STOCK_SHIPMENT_FK1
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT_ (PRODUCT_ID);

ALTER TABLE STOCK_ARRIVAL_
ADD CONSTRAINT STOCK_ARRIVAL_FK1
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT_ (PRODUCT_ID);

ALTER TABLE DEAL_DELIVERY_
ADD CONSTRAINT DEAL_DELIVERY_FK1
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT_ (PRODUCT_ID);

ALTER TABLE DEAL_DELIVERY_
ADD CONSTRAINT DEAL_DELIVERY_FK2
FOREIGN KEY (AGENT_ID)
REFERENCES AGENT_ (AGENT_ID);

ALTER TABLE DEAL_SHIPMENT_
ADD CONSTRAINT SHIPMENT_DELIVERY_FK1
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT_ (PRODUCT_ID);

ALTER TABLE DEAL_SHIPMENT_
ADD CONSTRAINT SHIPMENT_DELIVERY_FK2
FOREIGN KEY (AGENT_ID)
REFERENCES AGENT_ (AGENT_ID);

ALTER TABLE WAYBILL_DELIVERY_
ADD CONSTRAINT WAYBILL_DELIVERY_FK2
FOREIGN KEY (AGENT_ID)
REFERENCES AGENT_ (AGENT_ID);

ALTER TABLE WAYBILL_SHIPMENT_
ADD CONSTRAINT WAYBILL_SHIPMENT_FK2
FOREIGN KEY (AGENT_ID)
REFERENCES AGENT_ (AGENT_ID);

ALTER TABLE WB_PR_DELIVERY_
ADD CONSTRAINT WB_PR_DELIVERY_FK1
FOREIGN KEY (WB_ID)
REFERENCES WAYBILL_DELIVERY_ (WAYBILL_ID);

ALTER TABLE WB_PR_CHARGED_
ADD CONSTRAINT WB_PR_CHARGED_FK1
FOREIGN KEY (WB_ID)
REFERENCES WAYBILL_DELIVERY_ (WAYBILL_ID);

ALTER TABLE WB_PR_SHIPMENT_
ADD CONSTRAINT WB_PR_SHIPMENT__FK1
FOREIGN KEY (WB_ID)
REFERENCES WAYBILL_SHIPMENT_ (WAYBILL_ID);

ALTER TABLE WB_PR_DELIVERY_
ADD CONSTRAINT WB_PR_DELIVERY_FK2
FOREIGN KEY (PR_ID)
REFERENCES PRODUCT_ (PRODUCT_ID);

ALTER TABLE WB_PR_CHARGED_
ADD CONSTRAINT WB_PR_CHARGED_FK2
FOREIGN KEY (PR_ID)
REFERENCES PRODUCT_ (PRODUCT_ID);

ALTER TABLE WB_PR_SHIPMENT_
ADD CONSTRAINT WB_PR_SHIPMENT__FK2
FOREIGN KEY (PR_ID)
REFERENCES PRODUCT_ (PRODUCT_ID);